### ISSUE TITLE
injects visual detail？

### ISSUE THREAD

**Issue by FutureWithoutEnding** [WaveLi123/m-kplug#2]
In readme.md `m-kplug is an extension of the pre-trained model k-plug, which simply injects the visual signals to the decoder layer.`

Can you explain in detail how it is injected into the Decoder?

**Comment by WaveLi123** [comment]
Sorry for the late response. Here is a simple implementation: https://github.com/WaveLi123/m-kplug/blob/9888e67ac85888a16a6ad069d1de4b5877c92bc8/m_kplug/model/transformer_mass.py#L99

**Comment by FutureWithoutEnding** [comment]
The different from Standard Decoding is:
- input of standard decoder: **the preview token embedding**.
- input of visual decoder: **g * preview token embedding + (1 -g) * visual embedding**.

as the **picture** shows:
![image](https://github.com/WaveLi123/m-kplug/assets/53685945/bf682159-c34e-41ef-9c37-9eff7d2b8e3f)

that's the only difference, is right?
